version: 0.2

phases:
    install:
        commands:
            - pip install Pygments
            - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
            - dpkg -i hugo_0.48_Linux-64bit.deb
    build:
        commands:
            - hugo

    post_build:
        commands:
            - echo "Build complete"
artifacts:
    files:
        - '**/*'
    base-directory: public