version: 0.2

phases:
    install:
        commands:
            - pip install Pygments
            - wget https://github.com/gohugoio/hugo/releases/download/v0.55.1/hugo_0.55.1_Linux-64bit.deb
            - dpkg -i hugo_0.55.1_Linux-64bit.deb
    build:
        commands:
            - hugo
            - ls -ltr

    post_build:
        commands:
            - aws s3 sync --delete --acl public-read --delete --cache-control max-age=3600 public s3://ubersid.in
            - echo "Build complete"
